export const INIT_VIDEOS = 'INIT_VIDEOS'

export const VIDEOS_READY = 'VIDEOS_READY'
export const VIDEOS_INIT_SORT_READY = 'VIDEOS_INIT_SORT_READY'
export const VIDEOS_INIT_FILTER_READY = 'VIDEOS_INIT_FILTER_READY'

export const SORT_VIDEOS = 'SORT_VIDEOS'
export const SORT_VIDEOS_PUBLISH = 'SORT_VIDEOS_PUBLISH'
export const SORT_VIDEOS_VIEWS = 'SORT_VIDEOS_VIEWS'
export const SORT_VIDEOS_COLLECTCOUNT = 'SORT_VIDEOS_COLLECTCOUNT'

export const FILTER_VIDEOS_LENGTH = 'FILTER_VIDEOS_LENGTH'
export const LENGTH_ALL = 'LENGTH_ALL'
export const LENGTH_LESS_THEN_FOUR_MINS = 'LENGTH_LESS_THEN_FOUR_MINS'
export const LENGTH_LESS_THEN_FIVE_MINS = 'LENGTH_LESS_THEN_FIVE_MINS'
export const LENGTH_FIVE_TO_TEN_MINS = 'LENGTH_FIVE_TO_TEN_MINS'
export const LENGTH_MORE_THEN_TEN_MINS = 'LENGTH_MORE_THEN_TEN_MINS' 